// <!-- saved from url=(0028)https://smblott.org/keyboard.js on 2019/08/08 -->
// modified by gdh1995
// Generated by CoffeeScript 1.9.3
(function() {
  var count, n, ref;

  n = 30;

  count = 0;

  var table = document.getElementById("keyTable");
  var templateContent = document.querySelector("#rowTemplate").content;
  var preventAllCheckbox = document.querySelector("#preventAll");

  ref = "keydown keypress keyup".trim().split(/\s+/);
  for (var i = 0, len = ref.length; i < len; i++) {
    window.addEventListener(ref[i], onKeyboard, true)
  }
  function onKeyboard(event) {
        var element = document.importNode(templateContent, true);
        var type, modifiers;
        element.querySelector(".eventNumber").textContent = ++count;
        type = event.type;
        if (event.repeat) {
          type += ".repeat";
        }
        element.querySelector(".eventColumn").textContent = type;
        element.querySelector(".codeColumn").textContent = event.code;
        element.querySelector(".keyColumn").textContent = event.key;
        modifiers = [];
        if (event.ctrlKey) {
          modifiers.push("Control");
        }
        if (event.altKey) {
          modifiers.push("Alt");
        }
        if (event.metaKey) {
          modifiers.push("Meta");
        }
        if (event.shiftKey) {
          modifiers.push("Shift");
        }
        element.querySelector(".modifierColumn").textContent = modifiers.join("-");
        element.querySelector(".keyCodeColumn").textContent = event.keyCode;
        if (n < table.rows.length) {
          table.deleteRow(1);
        }
        table.appendChild(element);
        if (preventAllCheckbox) {
          event.preventDefault();
          event.stopImmediatePropagation();
        }
  }
}).call(this);
