"use strict";
// Generated by CoffeeScript 1.8.0
var Utils = {
  getCurrentVersion: function() {
    return chrome.runtime.getManifest().version;
  },
  _escapeRegex: /[&<>]/g,
  _escapeCallback: function(c, n) {
    n = c.charCodeAt(0);
    return (n === 60) ? "&lt;" : (n === 62) ? "&gt;" : "&amp;";
  },
  escapeHtml: function(s) {
    return s.replace(this._escapeRegex, this._escapeCallback);
  },
  _chromePrefixes: ["about", "view-source", "chrome-search", "chrome-extension", "data", "javascript"],
  hasChromePrefix: function(url) {
    var index = url.indexOf(':');
    return index > 3 && index < 17 && this._chromePrefixes.indexOf(url.substring(0, index)) !== -1;
  },
  _urlPrefix: /^[a-z]{3,}:\/\/./,
  hasOrdinaryUrlPrefix: function(url) {
    return this._urlPrefix.test(url);
  },
  isRefusingIncognito: function(url) {
    url = url.toLowerCase();
    if (url.startsWith('chrome://')) {
      return !url.startsWith("chrome://downloads/");
    }
    return url !== Settings.ChromeInnerNewTab && (url.startsWith('chrome') || !this._urlPrefix.test(url));
  },
  _hostRegex: /^(?:[^:]+(?::[^:]+)?@)?([^:]+|\[[^\]]+\])(?::\d+)?$/,
  _nonENTlds: ".\u4e2d\u56fd",
  _tlds: ["", "",
    ".ac.ad.ae.af.ag.ai.al.am.an.ao.aq.ar.as.at.au.aw.az.ba.bb.bd.be.bf.bg.bh.bi.bj.bm.bn.bo.br.bs.bt.bv.bw.by.bz.ca.cc.cd.cf.cg.ch.ci.ck.cl.cm.cn.co.cr.cu.cv.cx.cy.cz.de.dj.dk.dm.do.dz.ec.ee.eg.eh.er.es.et.eu.fi.fj.fk.fm.fo.fr.ga.gd.ge.gf.gg.gh.gi.gl.gm.gn.gp.gq.gr.gs.gt.gu.gw.gy.hk.hm.hn.hr.ht.hu.id.ie.il.im.in.io.iq.ir.is.it.je.jm.jo.jp.ke.kg.kh.ki.km.kn.kp.kr.kw.ky.kz.la.lb.lc.li.lk.lr.ls.lt.lu.lv.ly.ma.mc.md.me.mg.mh.mk.ml.mm.mn.mo.mp.mq.mr.ms.mt.mu.mv.mw.mx.my.mz.na.nc.ne.nf.ng.ni.nl.no.np.nr.nu.nz.om.pa.pe.pf.pg.ph.pk.pl.pm.pn.pr.ps.pt.pw.py.qa.re.ro.ru.rw.sa.sb.sc.sd.se.sg.sh.si.sj.sk.sl.sm.sn.so.sr.ss.st.sv.sy.sz.tc.td.tf.tg.th.tj.tk.tl.tm.tn.to.tp.tr.tt.tv.tw.tz.ua.ug.uk.um.us.uy.uz.va.vc.ve.vg.vi.vn.vu.wf.ws.ye.yt.yu.za.zm.zw",
    ".biz.cat.com.edu.gov.int.mil.mtn.net.org.pro.tel.xxx",
    ".aero.arpa.asia.club.coop.info.jobs.mobi.name.post",
    "",
    ".museum.travel"
  ],
  _ipRegex: /^(\d{1,3}\.){3}\d{1,3}$/,
  _spacesRegex: /[\s\u3000]+/g,
  _nonENTldRegex: /[^a-z]/,
  convertToUrl: function(string) {
    var type = -1, expected = 1, index, index0, oldString;
    oldString = string.replace(this._spacesRegex, ' ').trim();
    string = oldString.toLowerCase();
    index = string.indexOf(' ');
    if (index > 0 && string.startsWith("javascript:")) {
      type = 0;
    }
    else if (index > 0) {
      string = string.substring(0, index);
      if ((index = string.indexOf('/')) <= 0 || (index0 = string.indexOf(':')) === 0) {
        type = 2;
      }
      else if (index0 === -1) {}
      else if (string.substring(index0, index0 + 3) !== "://") {
        if (this._chromePrefixes.indexOf(string.substring(0, index0)) !== -1) {
          type = 2;
        } else {
          index0 = -1;
        }
      }
      else if (this._urlPrefix.test(string)) {
        expected = 0;
        if (string.startsWith("file:///")) {
          index0 = string.charCodeAt(8);
          type = (index0 > 32 && index0 !== 47) ? 0 : 2;
        }
      } else if (!this.startsWith("chrome")) {
        type = 2;
      }
      if (type < 0) {
        if (index0 > 0) {
          index0 += 3;
          index = string.indexOf('/', index0);
        } else {
          index0 = 0;
        }
        if (index > index0 && (type = string.charCodeAt(index + 1)) > 32 && type !== 47) {
          string = string.substring(index0, index);
          type = -1;
        } else {
          type = 2;
        }
      }
    }
    else if (this._urlPrefix.test(string)) {
      if (string.startsWith("file:") || string.startsWith("chrome:")) {
        type = 0;
      } else {
        index0 = string.indexOf(':') + 3;
        index = string.indexOf('/', index0);
        string = string.substring(index0, index !== -1 ? index : undefined);
        expected = 0;
      }
    } else if (this.hasChromePrefix(string)) {
      type = 0;
    } else {
      string = (index = string.indexOf('/')) !== -1 ? string.substring(0, index) : string;
    }
    if (type === -1) {
      type = this.isHost(string) ? expected : 2;
    }
    return type === 0 ? oldString : type === 1 ? ("http://" + oldString)
      : this.createSearchUrl(Settings.get("searchEnginesMap")["~"], oldString.split(' ')).url;
  },
  isHost: function(host) {
    var ret, arr, index;
    if (!(arr = this._hostRegex.exec(host))) {
      ret = true;
    } else if ((host = arr[1]).indexOf(':') !== -1 || host.endsWith("localhost")) {
      ret = true;
    } else if ((index = host.lastIndexOf('.')) === -1) {
      ret = false;
    } else if (this._ipRegex.test(host)) {
      ret = true;
    } else if (this._nonENTldRegex.test(host = host.substring(index + 1))) {
      ret = this._nonENTlds.indexOf(host) !== -1;
    } else if (host.length < this._tlds.length) {
      ret = this._tlds[host.length].indexOf(host) !== -1;
    } else {
      ret = false;
    }
    return ret;
  },
  _searchWordRegex: /%[sS]/g,
  createSearchUrl: function(pattern, query, $S) {
    if ($S != null ? ($S === true) : pattern.$S) {
      $S = query.join(' ');
    }
    if (pattern.$s) {
      query = query.map(encodeURIComponent).join('+');
    }
    query = pattern.url.replace(this._searchWordRegex, function(s) {
      return (s === "%s") ? query : $S;
    });
    return {
      url: query,
      $S: $S
    };
  },
  decodeURLPart: (function() {
    var decode = window.decodeURIComponent;
    return function(url) {
      try {
        url = decode(url);
      } catch (e) {
      }
      return url;
    };
  })(),
  distinctCharacters: function(str) {
    var char, unique, _i, _len, _ref;
    unique = "";
    _ref = str.split("").sort();
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      char = _ref[_i];
      if (0 > unique.indexOf(char)) {
        unique += char;
      }
    }
    return unique;
  },
  compareVersions: function(versionA, versionB) {
    var a, b, i, _i, _ref;
    versionA = versionA.split('.');
    versionB = versionB.split('.');
    for (i = 0, _ref = Math.max(versionA.length, versionB.length); i < _ref; ++i) {
      a = parseInt(versionA[i] || 0, 10);
      b = parseInt(versionB[i] || 0, 10);
      if (a < b) {
        return -1;
      } else if (a > b) {
        return 1;
      }
    }
    return 0;
  }
};

window.extend = function(hash1, hash2) {
  for (var key in hash2) {
    hash1[key] = hash2[key];
  }
  return hash1;
};
