// Generated by CoffeeScript 1.3.3
(function() {
  var Clipboard, root;

  Clipboard = {
    _textArea: undefined,
    createTextArea: function() {
      if (! this._textArea) {
        this._textArea = document.createElement("textarea");
        this._textArea.style.position = "absolute";
        this._textArea.style.left = "-100%";
      }
      return this._textArea;
    },
    copy: function(data) {
      var textArea = this.createTextArea();
      textArea.value = data;
      document.documentElement.appendChild(textArea);
      textArea.select();
      document.execCommand("Copy");
      document.documentElement.removeChild(textArea);
    },
    paste: function() {
      var textArea = this.createTextArea(), value;
      document.documentElement.appendChild(textArea);
      textArea.focus();
      document.execCommand("Paste");
      value = textArea.value;
      document.documentElement.removeChild(textArea);
      return value;
    }
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Clipboard = Clipboard;

}).call(this);
