"use strict";
// Generated by CoffeeScript 1.8.0
var Utils = {
  _div: undefined,
  _getDiv: function () {
    return this._div || (this._div = document.createElement("div"));
  },
  invokeCommandString: function(str, arg) {
    var components = str.split('.'), obj = window, _i, _len, _ref;
    for (_i = 0, _len = components.length - 1; _i < _len; _i++) {
      obj = obj[components[_i]];
    }
    obj[components[_len]](arg);
  },
  _wordHeadIs$: /\W\$\w/,
  templateVarRegex: /\{\{(\$?[A-Z\_a-z][0-9A-Z\_a-z]*)\}\}/g,
  makeListRenderBySplit: function(template, varRegex) {
    var varRegex = varRegex || this.templateVarRegex, o = null, a = template.split(varRegex),
    $ = (varRegex.source.indexOf("\\$") >= 0 && template.match(varRegex).join("").search(this._wordHeadIs$) >= 0),
    p = !$ ? null : {
      $index: 0
    }, f = $ ? function(w, i) {
      return i & 1 ? (w in o ? o[w] : w in p ? p[w] : "") : w;
    } : function(w, i) {
      return i & 1 ? (w in o ? o[w] : "") : w;
    }, m = $ ? function(i, j) {
      o = i;
      p.$index = "" + j;
      return a.map(f).join("");
    } : function(i) {
      o = i;
      return a.map(f).join("");
    };
    template = null;
    varRegex = null;
    return function(objectArray) {
      var html = objectArray.map(m).join("");
      o = null;
      return html;
    };
  },
  decodeTextFromHtml: function(html) {
    var tmp = this._getDiv();
    tmp.innerHTML = html;
    html = tmp.innerText;
    tmp.innerHTML = "";
    return html;
  },
  _spaceRegex: /[\xa0\u3000]/g,
  correctSpace: function(str) {
    return str.replace(this._spaceRegex, ' ');
  },
  _escapeRegex: /[&<>]/g,
  _escapeCallback: function(c, n) {
    n = c.charCodeAt(0);
    return (n === 60) ? "&lt;" : (n === 62) ? "&gt;" : "&amp;";
  },
  escapeHtml: function(s) {
    return s.replace(this._escapeRegex, this._escapeCallback);
  },
  createUniqueId: (function() {
    var i = 1;
    return function() {
      return ++i;
    };
  })(),
  decodeURL: function(url) {
    try {
      url = window.decodeURI(url);
    } catch (e) {
    }
    return url;
  },
  _upperRegex: /[A-Z]/,
  hasUpperCase: function(s) {
    return this._upperRegex.test(s);
  }
};

window.extend = function(hash1, hash2) {
  for (var key in hash2) {
    hash1[key] = hash2[key];
  }
  return hash1;
};
