// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.HandlerStack = (function() {

    function HandlerStack() {
      this.stack = [];
      this.counter = 0;
    }

    HandlerStack.prototype.genId = function() {
      return this.counter = ++this.counter & 0xffff;
    };

    HandlerStack.prototype.push = function(handler) {
      handler.id = this.genId();
      this.stack.push(handler);
      return handler.id;
    };

    HandlerStack.prototype.bubbleEvent = function(type, event) {
      var handler, i, passThrough, _i, _ref;
      for (i = _i = _ref = this.stack.length - 1; _i >= 0; i = _i += -1) {
        handler = this.stack[i];
        if (handler && handler[type]) {
          this.currentId = handler.id;
          passThrough = handler[type].call(this, event);
          if (!passThrough) {
            DomUtils.suppressEvent(event);
            return false;
          }
        }
      }
      return true;
    };

    HandlerStack.prototype.remove = function(id) {
      var handler, i, _i, _ref, _results;
      if (id == null) {
        id = this.currentId;
      }
      _results = [];
      for (i = _i = _ref = this.stack.length - 1; _i >= 0; i = _i += -1) {
        handler = this.stack[i];
        if (handler.id === id) {
          this.stack.splice(i, 1);
          break;
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return HandlerStack;

  })();

}).call(this);
