// Generated by CoffeeScript 1.8.0
(typeof exports !== "undefined" && exports !== null ? exports : window).KeyboardUtils = (
    (navigator.userAgent.indexOf("Mac") !== -1) ? "Mac"
  : (navigator.userAgent.indexOf("Linux") !== -1) ? "Linux"
  : "Windows"
);

(typeof exports !== "undefined" && exports !== null ? exports : window).KeyboardUtils = {
  platform: (typeof exports !== "undefined" && exports !== null ? exports : window).KeyboardUtils,
  keyCodes: {
    modifier: (((typeof exports !== "undefined" && exports !== null ? exports : window).KeyboardUtils === "Mac")
      ? "metaKey" : "ctrlKey"),
    esc: 27,
    backspace: 8,
    deleteKey: 46,
    enter: 13,
    space: 32,
    shiftKey: 16,
    ctrlKey: 17,
    left: 37,
    up: 38,
    right: 39,
    down: 40,
    f1: 112,
    f12: 123,
    tab: 9
  },
  keyNames: {
    37: "left",
    38: "up",
    39: "right",
    40: "down",
    112: "f1",
    113: "f2",
    114: "f3",
    115: "f4",
    116: "f5",
    117: "f6",
    118: "f7",
    119: "f8",
    120: "f9",
    121: "f10",
    122: "f11",
    123: "f12"
  },
  keyIdentifierCorrectionMap: {
    "U+00C0": ["U+0060", "U+007E"],
    "U+00BD": ["U+002D", "U+005F"],
    "U+00BB": ["U+003D", "U+002B"],
    "U+00DB": ["U+005B", "U+007B"],
    "U+00DD": ["U+005D", "U+007D"],
    "U+00DC": ["U+005C", "U+007C"],
    "U+00BA": ["U+003B", "U+003A"],
    "U+00DE": ["U+0027", "U+0022"],
    "U+00BC": ["U+002C", "U+003C"],
    "U+00BE": ["U+002E", "U+003E"],
    "U+00BF": ["U+002F", "U+003F"]
  },
  getKeyChar: function(event) {
    var keyIdentifier = event.keyIdentifier;
    if (! keyIdentifier.startsWith("U+")) {
      if (keyIdentifier = this.keyNames[event.keyCode]) {
        return event.shiftKey ? keyIdentifier.toUpperCase() : keyIdentifier;
      }
      return "";
    }
    if ((this.platform === "Windows" || this.platform === "Linux") && this.keyIdentifierCorrectionMap[keyIdentifier]) {
      keyIdentifier = this.keyIdentifierCorrectionMap[keyIdentifier][event.shiftKey ? 1 : 0];
    }
    keyIdentifier = String.fromCharCode(parseInt("0x" + keyIdentifier.substring(2)));
    return event.shiftKey ? keyIdentifier.toUpperCase() : keyIdentifier.toLowerCase();
  },
  isEscape: function(event) {
    return event.keyCode === this.keyCodes.esc;
  }
};

(typeof exports !== "undefined" && exports !== null ? exports : window).keyCodes = (typeof exports !== "undefined" && exports !== null ? exports : window).KeyboardUtils.keyCodes;