// Generated by CoffeeScript 1.8.0
(function() {
  var Utils, globalRoot, root, __slice = Array.prototype.slice;

  Utils = {
    _div: undefined,
    getCurrentVersion: function() {
      return chrome.runtime.getManifest().version;
    },
    invokeCommandString: function(str, argArray) {
      var component, components, func, obj, _i, _len, _ref;
      components = str.split('.');
      obj = window;
      _ref = components.slice(0, -1);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        component = _ref[_i];
        obj = obj[component];
      }
      func = obj[components.pop()];
      return func.apply(obj, argArray);
    },
    createElementFromHtml: function(html) {
      var tmp = Utils._div || (Utils._div = document.createElement("div"));
      tmp.innerHTML = html;
      html = tmp.firstChild;
      tmp.innerHTML = "";
      return html;
    },
    escapeHtml: function(string) {
      return string.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    },
    createUniqueId: (function() {
      var i = 0;
      return function() {
        return ++i;
      };
    })(),
    chromePrefixes: ["about:", "view-source:", "extension:", "chrome:", "chrome-search:", "chrome-extension:", "data:"],
    hasChromePrefix: function(url) {
      var prefix, _i, _len;
      if (0 < url.indexOf(":")) {
        for (_i = 0, _len = Utils.chromePrefixes.length; _i < _len; _i++) {
          prefix = Utils.chromePrefixes[_i];
          if (url.startsWith(prefix)) {
            return true;
          }
        }
      }
      return false;
    },
    urlPrefix: /^[a-z]{3,}:\/\/./i,
    hasFullUrlPrefix: function(url) {
      return Utils.urlPrefix.test(url);
    },
    createFullUrl: function(partialUrl) {
      if (Utils.urlPrefix.test(partialUrl)) {
        return partialUrl;
      } else {
        return "http://" + partialUrl;
      }
    },
    urlRegex: new RegExp('^(?:([^:]+)(?::([^:]+))?@)?([^:]+|\\[[^\\]]+\\])(?::(\\d+))?$'),
    longTlds: ['arpa', 'asia', 'coop', 'info', 'jobs', 'local', 'mobi', 'museum', 'name', 'onion'],
    specialHostNames: ['localhost'],
    isUrl: function(str) {
      var dottedParts, hostName, lastPart, match, _ref;
      if (str.indexOf(' ') >= 0) {
        return false;
      }
      if (Utils.urlPrefix.test(str)) {
        return true;
      }
      match = Utils.urlRegex.exec((str.split('/'))[0]);
      if (!match) {
        return false;
      }
      hostName = match[3];
      if (Utils.specialHostNames.indexOf(hostName) >= 0) {
        return true;
      }
      if (hostName.indexOf(':') >= 0) {
        return true;
      }
      dottedParts = hostName.split('.');
      if (dottedParts.length > 1) {
        lastPart = dottedParts.pop();
        if ((2 <= (_ref = lastPart.length) && _ref <= 3) || Utils.longTlds.indexOf(lastPart) >= 0) {
          return true;
        }
      }
      if (/^(\d{1,3}\.){3}\d{1,3}$/.test(hostName)) {
        return true;
      }
      return false;
    },
    createSearchUrl: function(baseUrl, query) {
      return baseUrl.replace(/%s/g, encodeURIComponent(query));
    },
    convertToUrl: function(string) {
      string = string.trim();
      if (Utils.hasChromePrefix(string)) {
        return string;
      } else if (Utils.isUrl(string)) {
        return Utils.createFullUrl(string);
      } else {
        return Utils.createSearchUrl(Settings.get("searchUrl"), string);
      }
    },
    isString: function(obj) {
      return typeof obj === 'string' || obj instanceof String;
    },
    compareVersions: function(versionA, versionB) {
      var a, b, i, _i, _ref;
      versionA = versionA.split(".");
      versionB = versionB.split(".");
      for (i = 0, _ref = Math.max(versionA.length, versionB.length); i < _ref; ++i) {
        a = parseInt(versionA[i] || 0, 10);
        b = parseInt(versionB[i] || 0, 10);
        if (a < b) {
          return -1;
        } else if (a > b) {
          return 1;
        }
      }
      return 0;
    },
    zip: function(arrays) {
      return arrays[0].map(function(_, i) {
        return arrays.map(function(array) {
          return array[i];
        });
      });
    },
    hasUpperCase: function(s) {
      return /[A-Z]/.test(s);
    }
  };

  Function.prototype.curry = function() {
    var fixedArguments = __slice.call(arguments, 0), fn = this;
    return function() {
      return fn.apply(this, fixedArguments.concat(__slice.call(arguments, 0)));
    };
  };

  Array.copy = function(array) {
    return __slice.call(array, 0);
  };

  String.prototype.startsWith || (String.prototype.startsWith = function(str) {
    return this.substring(0, str.length) === str;
  });

  globalRoot = typeof global !== "undefined" ? (window || global) : window;

  globalRoot.extend = function(hash1, hash2) {
    for (var key in hash2) {
      hash1[key] = hash2[key];
    }
    return hash1;
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Utils = Utils;

  window._DEBUG = true;

}).call(this);
