// Generated by CoffeeScript 1.3.3
(function() {
  var activatedElement, ensureScrollChange, getDimension, isRendered, root, scrollProperties;

  window.Scroller = root = {};

  activatedElement = null;

  root.init = function() {
    return handlerStack.push({
      DOMActivate: function() {
        return activatedElement = event.target;
      }
    });
  };

  scrollProperties = {
    x: {
      axisName: 'scrollLeft',
      max: 'scrollWidth',
      viewSize: 'clientHeight'
    },
    y: {
      axisName: 'scrollTop',
      max: 'scrollHeight',
      viewSize: 'clientWidth'
    }
  };

  getDimension = function(el, direction, name) {
    if (name === 'viewSize' && el === document.body) {
      if (direction === 'x') {
        return window.innerWidth;
      } else {
        return window.innerHeight;
      }
    } else {
      return el[scrollProperties[direction][name]];
    }
  };

  ensureScrollChange = function(direction, changeFn) {
    var axisName, element, lastElement, oldScrollValue, rect;
    axisName = scrollProperties[direction].axisName;
    element = activatedElement;
    while (true) {
      oldScrollValue = element[axisName];
      changeFn(element, axisName);
      lastElement = element;
      element = element.parentElement || document.body;
      if (!(lastElement[axisName] === oldScrollValue && lastElement !== document.body)) {
        break;
      }
    }
    rect = activatedElement.getBoundingClientRect();
    if (rect.bottom < 0 || rect.top > window.innerHeight || rect.right < 0 || rect.left > window.innerWidth) {
      return activatedElement = lastElement;
    }
  };

  root.scrollBy = function(direction, amount, factor) {
    if (factor == null) {
      factor = 1;
    }
    if (!document.body && amount instanceof Number) {
      if (direction === "x") {
        window.scrollBy(amount, 0);
      } else {
        window.scrollBy(0, amount);
      }
      return;
    }
    if (!activatedElement || !isRendered(activatedElement)) {
      activatedElement = document.body;
    }
    if (Utils.isString(amount)) {
      amount = getDimension(activatedElement, direction, amount);
    }
    amount *= factor;
    if (amount !== 0) {
      return ensureScrollChange(direction, function(element, axisName) {
        return element[axisName] += amount;
      });
    }
  };

  root.scrollTo = function(direction, pos) {
    if (!document.body) {
      return;
    }
    if (!activatedElement || !isRendered(activatedElement)) {
      activatedElement = document.body;
    }
    if (Utils.isString(pos)) {
      pos = getDimension(activatedElement, direction, pos);
    }
    return ensureScrollChange(direction, function(element, axisName) {
      return element[axisName] = pos;
    });
  };

  isRendered = function(element) {
    var computedStyle;
    computedStyle = window.getComputedStyle(element, null);
    return !(computedStyle.getPropertyValue("visibility") !== "visible" || computedStyle.getPropertyValue("display") === "none");
  };

}).call(this);
