// Generated by CoffeeScript 1.8.0
(function() {
  var content_scripts, insertLocation, insertLink, insertJS, scriptInfo, _i, _j, _len, _len1, _ref;
  content_scripts = chrome.runtime.getManifest().content_scripts;
  insertLocation = document.querySelector('script[src*="content_script_loader.js"]') || document.head.firstChild;
  insertLink = function(src) {
    var styleElement = document.createElement("link");
    styleElement.rel = "stylesheet";
    styleElement.type = "text/css";
    styleElement.href = src;
    insertLocation.parentElement.insertBefore(styleElement, insertLocation);
  };
  insertJS = function(src) {
    var scriptElement = document.createElement("script");
    scriptElement.type = "text/javascript";
    scriptElement.async = false;
    scriptElement.src = "/" + _ref[_j];
    insertLocation.parentElement.insertBefore(scriptElement, insertLocation);
  };
  for (_i = 0, _len = content_scripts.length; _i < _len; _i++) {
    scriptInfo = content_scripts[_i];
    if (scriptInfo.matches.indexOf("<all_urls>") === -1) {
      continue;
    }
    if (scriptInfo.css) {
      _ref = scriptInfo.css;
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        insertLink("/" + _ref[_j]);
      }
    }
    if (scriptInfo.js) {
      _ref = scriptInfo.js;
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        insertJS("/" + _ref[_j]);
      }
    }
  }
  insertLink("content_scripts/vomnibar.css");
})();
