// Generated by CoffeeScript 1.8.0
(function() {
  var $, CheckBoxOption, ExclusionRulesOption, NonEmptyTextOption, NumberOption, Option, TextOption, activateHelpDialog, bgSettings, enableSaveButton, maintainLinkHintsView, toggleAdvancedOptions,
    __hasProp = Object.prototype.hasOwnProperty,
    __extends = function(child, parent) {
      for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; }
      function ctor() { this.constructor = child; } ctor.prototype = parent.prototype;
      child.prototype = new ctor(); child.__super__ = parent.prototype;
      return child;
    };

  $ = function(id) {
    return document.getElementById(id);
  };

  bgSettings = chrome.extension.getBackgroundPage().Settings;

  Option = (function() {
    Option.all = [];

    function Option(field, enableSaveButton) {
      this.field = field;
      this.element = $(this.field);
      this.element.addEventListener("change", enableSaveButton);
      this.fetch();
      Option.all.push(this);
    }

    Option.prototype.fetch = function() {
      this.populateElement(this.previous = bgSettings.get(this.field));
      return this.previous;
    };

    Option.prototype.save = function() {
      var value = this.readValueFromElement();
      if (!this.areEqual(value, this.previous)) {
        bgSettings.set(this.field, this.previous = value);
      }
    };

    Option.prototype.areEqual = function(a, b) {
      return a === b;
    };

    Option.prototype.restoreToDefault = function() {
      bgSettings.clear(this.field);
      return this.fetch();
    };

    Option.saveOptions = function() {
      Option.all.forEach(function(option) {
        option.save();
      });
      var saveBtn = $("saveOptions");
      saveBtn.disabled = true;
      saveBtn.innerHTML = "No Changes";
    };

    return Option;

  })();

  NumberOption = (function(_super) {
    __extends(NumberOption, _super);

    function NumberOption() {
      return NumberOption.__super__.constructor.apply(this, arguments);
    }

    NumberOption.prototype.populateElement = function(value) {
      return this.element.value = value;
    };

    NumberOption.prototype.readValueFromElement = function() {
      return parseFloat(this.element.value);
    };

    return NumberOption;

  })(Option);

  TextOption = (function(_super) {
    __extends(TextOption, _super);

    function TextOption(field, enableSaveButton) {
      TextOption.__super__.constructor.call(this, field, enableSaveButton);
      this.element.addEventListener("input", enableSaveButton);
    }

    TextOption.prototype.populateElement = function(value) {
      return this.element.value = value.replace(/\n /g, '\n\xa0');
    };

    TextOption.prototype.readValueFromElement = function() {
      return this.element.value.trim().replace(/\xa0/g, ' ');
    };

    return TextOption;

  })(Option);

  NonEmptyTextOption = (function(_super) {
    __extends(NonEmptyTextOption, _super);

    function NonEmptyTextOption(field, enableSaveButton) {
      NonEmptyTextOption.__super__.constructor.call(this, field, enableSaveButton);
      this.element.addEventListener("input", enableSaveButton);
    }

    NonEmptyTextOption.prototype.populateElement = function(value) {
      return this.element.value = value.replace(/\n /g, '\n\xa0');
    };

    NonEmptyTextOption.prototype.readValueFromElement = function() {
      var value = this.element.value.trim().replace(/\xa0/g, ' ');
      if (value) {
        return value;
      } else {
        return this.restoreToDefault();
      }
    };

    return NonEmptyTextOption;

  })(Option);

  CheckBoxOption = (function(_super) {
    __extends(CheckBoxOption, _super);

    function CheckBoxOption() {
      return CheckBoxOption.__super__.constructor.apply(this, arguments);
    }

    CheckBoxOption.prototype.populateElement = function(value) {
      return this.element.checked = value;
    };

    CheckBoxOption.prototype.readValueFromElement = function() {
      return this.element.checked;
    };

    return CheckBoxOption;

  })(Option);

  ExclusionRulesOption = (function(_super) {
    __extends(ExclusionRulesOption, _super);

    function ExclusionRulesOption() {
      ExclusionRulesOption.__super__.constructor.apply(this, arguments);
      $("exclusionAddButton").addEventListener("click", (function(_this) {
        return function(event) {
          var exclusionScrollBox;
          _this.appendRule({
            pattern: "",
            passKeys: ""
          });
          _this.element.children[_this.element.children.length - 1].children[0].children[0].focus();
          exclusionScrollBox = $("exclusionScrollBox");
          return exclusionScrollBox.scrollTop = exclusionScrollBox.scrollHeight;
        };
      })(this));
    }

    ExclusionRulesOption.prototype.populateElement = function(rules) {
      var rule, _i, _len;
      while (this.element.firstChild) {
        this.element.removeChild(this.element.firstChild);
      }
      for (_i = 0, _len = rules.length; _i < _len; _i++) {
        rule = rules[_i];
        this.appendRule(rule);
      }
    };

    ExclusionRulesOption.prototype.appendRule = function(rule) {
      var element, field, remove, row, _i, _j, _len, _ref, _ref1;
      row = document.importNode(document.querySelector('#exclusionRuleTemplate').content, true);
      _ref = ["pattern", "passKeys"];
      _ref1 = ["input", "change"];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        field = _ref[_i];
        element = row.querySelector("." + field);
        element.value = rule[field];
        for (_j = _ref1.length; 0 <= --_j; ) {
          element.addEventListener(_ref1[_j], enableSaveButton);
        }
      }
      row.querySelector(".exclusionRemoveButton").addEventListener("click", function(event) {
        var row1 = event.target.parentNode.parentNode;
        row1.parentNode.removeChild(row1);
        enableSaveButton();
      });
      this.element.appendChild(row);
    };

    ExclusionRulesOption.prototype.readValueFromElement = function() {
      var children, passKeys, pattern, rules, _i, _len, _ref;
      rules = [];
      _ref = this.element.getElementsByClassName("exclusionRuleTemplateInstance");
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        children = _ref[_i].children;
        pattern = children[0].firstChild.value.trim();
        if (!pattern) {
          continue;
        }
        passKeys = children[1].firstChild.value.trim();
        rules.push({
          pattern: pattern,
          passKeys: passKeys
        });
      }
      if (JSON.stringify(rules) === JSON.stringify(bgSettings.defaults.exclusionRules)) {
        rules = bgSettings.defaults.exclusionRules;
      }
      return rules;
    };

    ExclusionRulesOption.prototype.flatten = function(rule) {
      return (rule && rule.pattern) ? (rule.pattern + "\r" + rule.passKeys) : "";
    };

    ExclusionRulesOption.prototype.areEqual = function(a, b) {
      return a.map(this.flatten).join("\n") === b.map(this.flatten).join("\n");
    };

    return ExclusionRulesOption;

  })(Option);

  enableSaveButton = function() {
    var saveBtn = $("saveOptions");
    saveBtn.removeAttribute("disabled");
    saveBtn.innerHTML = "Save Changes";
  };

  maintainLinkHintsView = function() {
    var hide, show;
    hide = function(el) {
      el.parentNode.parentNode.style.display = "none";
    };
    show = function(el) {
      el.parentNode.parentNode.style.display = "table-row";
    };
    if ($("filterLinkHints").checked) {
      hide($("linkHintCharacters"));
      show($("linkHintNumbers"));
    } else {
      show($("linkHintCharacters"));
      hide($("linkHintNumbers"));
    }
  };

  var _advancedMode = false;
  toggleAdvancedOptions = function(event) {
    if (_advancedMode) {
      $("advancedOptions").style.display = "none";
      $("advancedOptionsLink").innerHTML = "Show advanced options&hellip;";
    } else {
      $("advancedOptions").style.display = "table-row-group";
      $("advancedOptionsLink").innerHTML = "Hide advanced options";
    }
    _advancedMode = !_advancedMode;
    event.preventDefault();
    document.activeElement.blur();
  };

  activateHelpDialog = function() {
    showHelpDialog(chrome.extension.getBackgroundPage().helpDialogHtml(true, true, "Command Listing"), frameId);
    document.activeElement.blur();
  };

  document.addEventListener("DOMContentLoaded", function() {
    var element, name, type, _i, _len, _ref, _ref1;
    _ref = {
      exclusionRules: ExclusionRulesOption,
      filterLinkHints: CheckBoxOption,
      hideHud: CheckBoxOption,
      keyMappings: TextOption,
      linkHintCharacters: NonEmptyTextOption,
      linkHintNumbers: NonEmptyTextOption,
      newTabUrl: NonEmptyTextOption,
      nextPatterns: NonEmptyTextOption,
      previousPatterns: NonEmptyTextOption,
      regexFindMode: CheckBoxOption,
      scrollStepSize: NumberOption,
      smoothScroll: CheckBoxOption,
      searchEngines: TextOption,
      searchUrl: NonEmptyTextOption,
      userDefinedLinkHintCss: TextOption
    };
    for (name in _ref) {
      type = _ref[name];
      new type(name, enableSaveButton);
    }
    $("saveOptions").addEventListener("click", Option.saveOptions);
    $("advancedOptionsLink").addEventListener("click", toggleAdvancedOptions);
    $("showCommands").addEventListener("click", activateHelpDialog);
    $("filterLinkHints").addEventListener("click", maintainLinkHintsView);
    _ref1 = document.getElementsByClassName("nonEmptyTextOption");
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      element = _ref1[_i];
      element.className = element.className + " example info";
      element.innerHTML = "Leave empty to reset this option.";
    }
    maintainLinkHintsView();
    window.onbeforeunload = function() {
      if (!$("saveOptions").disabled) {
        return "You have unsaved changes to options.";
      }
    };
    document.addEventListener("keyup", function(event) {
      if ((event.ctrlKey || event.metaKey) && event.keyCode === 13) {
        if (document.activeElement && document.activeElement.blur) {
          document.activeElement.blur();
        }
        Option.saveOptions();
      }
    });
  });

})();
