// Generated by CoffeeScript 1.8.0
(function() {
  var Exclusions, RegexpCache, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  RegexpCache = {
    _cache: {},
    get: function(pattern) {
      return this._cache[pattern] || (this._cache[pattern] = new RegExp("^" + pattern.replace(/\*/g, ".*") + "$"));
    }
  };

  root.Exclusions = Exclusions = {
    rules: Settings.get("exclusionRules"),
    getRule: function(url) {
      var rule, _i, _len, _ref;
      _ref = this.rules;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        rule = _ref[_i];
        if (url.match(RegexpCache.get(rule.pattern))) {
          return rule;
        }
      }
      return null;
    },
    setRules: function(rules) {
      this.rules = rules.filter(function(rule) {
        return rule && rule.pattern;
      });
      Settings.set("exclusionRules", this.rules);
    },
    postUpdateHook: function(rules) {
      this.rules = rules;
    },
    updateOrAdd: function(newRule) {
      var seen = false;
      this.rules.push(newRule);
      this.setRules(this.rules.map(function(rule) {
        if (rule.pattern === newRule.pattern) {
          if (seen) {
            return null;
          } else {
            seen = true;
            return newRule;
          }
        } else {
          return rule;
        }
      }));
    },
    remove: function(pattern) {
      this.setRules(this.rules.filter(function(rule) {
        return rule && rule.pattern !== pattern;
      }));
    }
  };

  if (false && Settings.has("excludedUrlsBackup")) {
    Settings.clear("exclusionRules");
    Settings.set("excludedUrls", Settings.get("excludedUrlsBackup"));
  }

  if (!Settings.has("exclusionRules") && Settings.has("excludedUrls")) {
    Exclusions.setRules((function(lines) {
      var line, parse, _i, _len, _ref, results;
      _ref = lines.trim().split("\n");
      results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        line = _ref[_i].trim();
        if (line.length && line.indexOf("#") !== 0 && line.indexOf('"') !== 0) {
          parse = line.split(/\s+/);
          results.push({
            pattern: parse[0],
            passKeys: parse.slice(1).join("")
          });
        }
      }
      return results;
    })(Settings.get("excludedUrls")));
    if (!Settings.has("excludedUrlsBackup")) {
      Settings.set("excludedUrlsBackup", Settings.get("excludedUrls"));
    }
    Settings.clear("excludedUrls");
  }

}).call(this);
