// Generated by CoffeeScript 1.8.0
window.Marks = {};

Marks._marks = {};

Marks.create = function(req, tab) {
  Marks._marks[req.markName] = {
    tabId: tab.id,
    scrollX: req.scrollX,
    scrollY: req.scrollY
  };
};

chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
  if (changeInfo.status === "loading" && changeInfo.url != null &&
      !Utils.isTabWithSameUrl(tabInfoMap[tabId], tab)) {
    Marks._removeMarksForTab(tabId);
  }
});

Marks._removeMarksForTab = function(id) {
  var marks = Marks._marks, markName;
  for (var markName in marks) {
    if (marks[markName].tabId === id) {
      delete marks[markName];
    }
  }
};

Marks.goTo = function(req, tab) {
  var mark = Marks._marks[req.markName];
  chrome.tabs.update(mark.tabId, {
    selected: true
  });
  chrome.tabs.sendMessage(mark.tabId, {
    name: "setScrollPosition",
    scrollX: mark.scrollX,
    scrollY: mark.scrollY
  });
  chrome.tabs.sendMessage(mark.tabId, {
    name: "showHUDforDuration",
    text: "Jumped to global mark '" + req.markName + "'",
    duration: 1000
  });
};

chrome.tabs.onRemoved.addListener(Marks._removeMarksForTab);
