// Generated by CoffeeScript 1.8.0
(function() {
  var marks, removeMarksForTab, root;

  root = window.Marks = {};

  marks = {};

  root.create = function(req, tab) {
    marks[req.markName] = {
      tabId: tab.id,
      scrollX: req.scrollX,
      scrollY: req.scrollY
    };
  };

  chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
    if (changeInfo.status === "loading" && changeInfo.url != null &&
        !Utils.isTabWithSameUrl(tabInfoMap[tabId], tab)) {
      removeMarksForTab(tabId);
    }
  });

  removeMarksForTab = function(id) {
    for (var markName in marks) {
      if (marks[markName].tabId === id) {
        delete marks[markName];
      }
    }
  };

  root.goTo = function(req, tab) {
    var mark = marks[req.markName];
    chrome.tabs.update(mark.tabId, {
      selected: true
    });
    chrome.tabs.sendMessage(mark.tabId, {
      name: "setScrollPosition",
      scrollX: mark.scrollX,
      scrollY: mark.scrollY
    });
    chrome.tabs.sendMessage(mark.tabId, {
      name: "showHUDforDuration",
      text: "Jumped to global mark '" + req.markName + "'",
      duration: 1000
    });
  };

  chrome.tabs.onRemoved.addListener(removeMarksForTab);

}).call(this);
